### ISSUE TITLE
Hi i need some help how can i contact you sorry to raise an issue in this way its because there is no other way to contact you 

### ISSUE THREAD

**Issue by jivthesh** [junkor-1011/linux_setting_environments#1]
Hi i need some help how can i contact you sorry to raise an issue in this way its because there is no other way to contact you , are u der in discord?

**Comment by junkor-1011** [comment]
In short, what is your point or requirement?

**Comment by jivthesh** [comment]
I need help in using Leaflet Ant Path to a set of GEOJSON data can we use this plugin with GEOJON instead of coordinates only .

**Comment by junkor-1011** [comment]
@jivthesh 
Firstly, **I'm NOT an expert of [leaflet-antpath](https://github.com/rubenspgcavalcante/leaflet-ant-path)** although I have used it before.
I think this issue is not appropriate.

If you need detailed or precise help, you should ask other experts for help (in other place, such as [leaflet-ant-path issues](https://github.com/rubenspgcavalcante/leaflet-ant-path/issues) ).

------

Converting and extracting GeoJson features to coordinates array by using filter, map, forEach, and others may be one of the solution.
Below is a part of my past sample code, for example:

```javascript
                geojson.features.forEach((x) => {
                  const lines =
                    x.geometry.type === "LineString"
                      ? [x.geometry.coordinates]
                      : x.geometry.coordinates;
                  lines.forEach((line) => {
                    // forward
                    const line_fw = turf.lineOffset(
                      turf.lineString(line),
                      -18,
                      { units: "meters" }
                    ).geometry.coordinates;
                    div.group.addLayer(
                      L.polyline
                        .antPath(
                          line_fw.map((a) => [a[1], a[0]]),
                          {
                            color: "blue",
                            weight: 3.5,
                            opacity: 0.7,
                            delay: 4500,
                            hardwareAccelerated: true,
                            reverse: false,
                          }
                        )
                        .bindPopup("forward: " + JSON.stringify(x.properties))
                    );
```

That's all I can help you.
